module.exports.streets = [
	'Allen Street',
	'Ann Street',
	'Astor Place',
	'Barrow Street',
	'Bayard Street',
	'Beach Street',
	'Beak Street',
	'Beekman Place',
	'William Street',
	'Bethune Street',
	'Bleecker Street',
	'Bogardus Place',
	'Bradhurst Avenue',
	'Broome Street',
	'Cabrini Boulevard',
	'Catherine Street',
	'Charles Street',
	'Charlton Street',
	'Christopher Street',
	'Colonel Robert Magaw Place',
	'Columbus Circle',
	'Cortlandt Street',
	'Delancey Street',
	'Dyckman Street',
	'Eldridge Street',
	'Forsyth Street',
	'Fulton Street',
	'Gay Street',
	'George Balanchine Way',
	'Great Jones Street',
	'Greene Street',
	'Henry Street',
	'Horatio Street',
	'Houston Street',
	'Irving Place',
	'Jane Street',
	'Jefferson Street',
	'Peter Jennings Way',
	'Juan Pablo Duarte Boulevard',
	'Lafayette Street',
	'LaGuardia Place',
	'Lenox Avenue',
	'Leonard Harper Way',
	'Leroy Street',
	'Ludlow Street',
	'MacDougal Street',
	'Madison Avenue and Madison Street',
	'Malcolm X Boulevard',
	'Mercer Street',
	'Monroe Street',
	'Morton Street',
	'Nassau Street',
	'North Moore Street',
	'Perry Street',
	'Rivington Street',
	'Robert F. Wagner',
	'Rutgers Street',
	"St. Mark's Place",
	'Saint Nicholas Avenue',
	'Stanton Street',
	'Stuyvesant Street',
	'Sullivan Street',
	'Thompson Street',
	'Tiemann Place',
	'Vanderbilt Avenue',
	'Varick Street',
	'Vesey Street',
	'Washington Street',
	'Wooster Street',
	'Worth Street',
	//
	'Chatham Square',
	'Duffy Square',
	'Hanover Square',
	'Herald Square',
	'Lincoln Square',
	'Madison Square',
	'Margaret Sanger Square',
	'Times Square',
	'Tompkins Square Park',
	'Verdi Square',
	'Washington Square Park',
	'Worth Square',
	//
	'Bartow Avenue',
	'Bainbridge Avenue',
	'Bruckner Boulevard',
	'Corsa Avenue',
	'Orio J. Palmer Way',
	'Sean Carrington Way',
	'DJ Scott La Rock Boulevard',
	'Donald Byrd Way',
	'Elias Karmon Way',
	'Elmo Hope Way',
	'Emmanuel Mensah Way',
	'Hillman Avenue',
	'Hull Ave',
	'Kalief Browder Way',
	'Major Deegan Expressway',
	'Perry Avenue',
	'Rivera Avenue',
	'Rose Feiss Boulevard',
	'Seabury Avenue',
	'Seven Brothers Square',
	'Sheridan Avenue',
	'Southern Boulevard',
	'Decatur Ave',
];
